default:
  adapter: postgresql
  host: ENV["DB_HOST"]
  port: 5432
  username: ENV["DB_USERNAME"]
  password: ENV["DB_PASSWORD"]
  database: ENV["DB_DATABASE"]
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
